/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {

        Character NPC = new Character();
        IO.println("Digite em sequencia separado por (,) o attack,speed,inteligence,agility,dex,luck,maxhealth");
        NPC.setCharacter("6,5,7,3,1,7,56");
        IO.println("Raridade do item encontrado: "+NPC.openChest());
        IO.println("Dano infringido:"+NPC.characterAttack());
    }
}
