/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo.app;

import ads.poo.list.LinkedList;

import static ads.poo.utilities.StringUtils.join;
import static ads.poo.utilities.StringUtils.split;
import static ads.poo.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        String nome= IO.readln("Entre com seu nome: ");
        IO.println("Olá "+nome);
        int i=0;
        for(String aux: args){
            if (aux.equals("POO")) {
                IO.println("Acertou");
            } else{
                i++;
            }
        }
        IO.println("Total de argumentos diferentes de POO: "+i);
    }
}
