/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.ArrayList;

public class App {
    public static void main(String[] args) {
        ArrayList<String> lista = new ArrayList();
        lista.add("POO");
        lista.add("ADS");
        lista.add("IFSC");

        lista.add(1,"SJE");

        //for i
        for (int i = 0; i < lista.size(); i++) {
            IO.println(lista.get(i));
        }
        //for each
        for(String e :lista){
            IO.println(e);
        }
        //lambda
        lista.forEach(e -> IO.println(e));
        //method reference
        lista.forEach(IO::println);
    }
}
