/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.ArrayList;

public class App {
    public static void main(String[] args) {
        ArrayList<Pessoa> agenda = new ArrayList();

        agenda.add(new Pessoa("Lucas Godoy","Lucas.doy@aluno.ifsc.edu.br"));
        agenda.add(new Pessoa("Bruno","Bruno@aluno.ifsc.edu.br"));



        agenda.removeIf(e ->e.getNome().equals("Bruno"));


        agenda.forEach(IO::println);

        //for i
        //for (int i = 0; i < lista.size(); i++) {
        //    IO.println(lista.get(i));
        // }
        //for each
        //for(String e :lista){
        //    IO.println(e);
        //}
        //lambda
        //lista.forEach(e -> IO.println(e));
        //method reference
        //lista.forEach(IO::println);
    }
}
