/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {
        Caneta a =new Caneta("azul",100);
        Caneta b =new Caneta(50);
        Caneta c =new Caneta();
    }
}
