/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;


 import java.util.ArrayList;
 import java.util.HashMap;

public class App {

    public static void main(String[] args) {

        HashMap<String,String> mapa=new HashMap<>();
        mapa.put("123","Juca");
        mapa.put("456","Ana");
        mapa.put("789","Pedro");


        String nome =mapa.get("456");
        mapa.forEach((chave,valor)-> IO.println("chave: "+chave+", valor: "+ valor));

        for(var elemento: mapa.entrySet()){
            IO.println("chave: "+elemento.getKey());
            IO.println(", valor: "+elemento.getValue());
        }
        mapa.remove("456"); //remoção pela chave

        mapa.values().removeIf(e->e.equals("Juca"));// remove todos com valor igual Juca
    }
}
