/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;


 import java.lang.classfile.instruction.SwitchCase;
 import java.util.ArrayList;
 import java.util.HashMap;

public class App {

    static HashMap<String, Livro> livros= new HashMap<>();

    public static void main(String[] args) {
        //HashMap<String,String> mapa=new HashMap<>();
        //mapa.put("123","Juca");
        //mapa.put("456","Ana");
        //mapa.put("789","Pedro");

        //String nome =mapa.get("456");
        //mapa.forEach((chave,valor)-> IO.println("chave: "+chave+", valor: "+ valor));

        //for(var elemento: mapa.entrySet()){
        //    IO.println("chave: "+elemento.getKey());
        //    IO.println(", valor: "+elemento.getValue());
        //}
        //mapa.remove("456"); //remoção pela chave
        //mapa.values().removeIf(e->e.equals("Juca"));// remove todos com valor igual Juca
            boolean sair=false;
            String buffer;
            int digitado=0;
            while(!sair) {
                IO.println("<----------Sistema teste---------->");
                switch (digitado){
                    case 1:
                        cadastrar();
                        break;
                    case 2:
                        listar();
                        break;
                    case 3:

                        break;
                    case 4:

                        break;
                    case 5:

                        break;
                    case 6:

                        break;
                    case 7:

                        break;
                    case 8:

                        break;
                    default:
                        listarfuncoes();
                        break;
                }
                buffer=IO.readln("Digite sua seleção: ");
                digitado=Integer.parseInt(buffer);
            }


    }
    public static void cadastrar(){
        String ISBN =IO.readln("Digite o ISBN do livro: ");
        while(livros.containsKey(ISBN)){
            IO.println("ISBN já cadastrado, tente novamente");
            ISBN =IO.readln("Digite o ISBN do livro: ");
        }
        String Autor =IO.readln("Digite o Autor do livro: ");
        String Titulo =IO.readln("Digite o Titulo do livro: ");
        int ano =Integer.parseInt(IO.readln("Digite o ano de lançamento do livro: "));
        Livro cadastrado =new Livro(ano,Autor,Titulo);
        livros.put(ISBN,cadastrado);
    }
    public static void listar(){
        IO.println("<--------------Lista de livros---------->");
        livros.forEach((key,Livro)->{
            IO.println("ISBN: "+key);
            IO.println("Titulo: "+Livro.getTiulo());
            IO.println("----------------------------------------");
        });
    }
    public static void listarfuncoes(){
        IO.println("1.Cadastrar um livro");
        IO.println("2.Listar livros");
        IO.println("3.Consultar pelo ISBN");
        IO.println("4.Consultar pelo Autor");
        IO.println("5.Consultar pelo ano de publicação");
        IO.println("6.Atualizar dados de um livro");
        IO.println("7.Remover um livro");
        IO.println("8.Sair do sistema");
    }
}
