/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {


    public static void main(String args[]) {
        Contador ct = new Contador();
        ct.Atribuirvalor(10);
        ct.Incrementarvalor();
        IO.println("O valor do contador é: " +ct.Obtervalor());



    }
}
